New Vel monitor #11
wisniax/RoverControlApp pull request #17
Opened 2024-05-17 12:58 UTC by wojtek20032

2024-05-18 18:22 UTC, wisniax requested changes
Missing settings integration for wheel's ID setup + comments

2024-05-18 18:22 UTC, wisniax commented on Core/MqttClasses.cs
> +	}
Inconsistent spacing and indentation

2024-05-18 18:22 UTC, wisniax commented on MVVM/View/MainView.tscn
Needs to be updated to current master, and then changed...

2024-05-18 18:22 UTC, wisniax commented on MVVM/View/VelMonitor.tscn
Not sure whether this scales with resolution change

2024-05-18 18:22 UTC, wisniax commented on MVVM/ViewModel/VelMonitor.cs
Formatting? Spacings? Please follow the previous convention.
Also doesn't seem to support 4 wheels just yet, unless i'm mistaken

2024-11-10 11:54 UTC, AlvaroBajceps commented
Closing due to no activity.

2024-11-10 11:54 UTC, closed without merging