Convert static stuff to instance
wisniax/RoverControlApp pull request #21
Opened 2024-05-30 11:46 UTC by AlvaroBajceps

TBD

2024-07-18 10:24 UTC, wisniax requested changes
Woah that took some time.
There are 2 things described that really need to be addressed.
Good Job 🥇

2024-07-18 12:58 UTC, AlvaroBajceps commented on Core/EventLogger.cs
> +using static OpenCvSharp.ML.DTrees;
Addressed in 4468e8a

2024-07-18 13:06 UTC, AlvaroBajceps commented on MVVM/Model/MissionSetPoint.cs
> +    public class MissionSetPoint
Addressed in 6ce1587

2024-07-18 13:06 UTC, AlvaroBajceps commented on MVVM/Model/MissionStatus.cs
> +    public class MissionStatus
Addressed in 6ce1587

2024-07-18 13:12 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +	void OnSettingsCategotyChanged(StringName property)
categoty. 37a66aa5197c92ca13e7400b3e3d267e974b5440

2024-07-18 13:19 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +		var (newTopic, newQos) =
Have it your way. cd2af3056d848adb85271c33ae9a79fd3029f774
Next time use suggestion block.

2024-07-18 13:25 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +	 * Methods for Mqtt managment
managment. ea458570fa1d2ed6ccb2e20c1b2771914400abbf

2024-07-18 13:30 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +	private bool MqStop(bool awaitFullStop = false)
Have it your way. eabcb3c20f3e9149cec2404b9f493bb6e2df3de7
Next time use suggestion block.

2024-07-18 14:29 UTC, AlvaroBajceps commented on MVVM/Model/TargetObjectMirror.cs
> +public class TargetObjectMirror
No. 418286b7ba5117a0c812688c0270c338cdef6a90

2024-07-18 14:33 UTC, AlvaroBajceps commented on Core/JSONConverters/CameraConnectionConverter.cs
> +	static readonly CameraConnection @default = new();
c634301a036a6cc2144e4972ef7fbb75ac38fb61

2024-07-18 14:36 UTC, AlvaroBajceps commented on MVVM/Model/RoverCommunication.cs
> +		protected virtual void Dispose(bool disposing)
Have it your way. 51a4ac7de24fa5c24b2e467f9c38fd1d05aa59e0
Use suggestion block!

2024-07-18 14:38 UTC, AlvaroBajceps commented on MVVM/ViewModel/MainViewModel.cs
> +		private ImageTexture? imTexture;
a09f80682fbefb4a2eeab5dfb6f8fa69adc17ea0

2024-07-18 14:41 UTC, AlvaroBajceps commented on MVVM/Model/MqttNodeMessage.cs
Have it your way. ab667fdfd5f43cd437b0754d0db8ca661cfccb1d
Use suggestion block plz.

2024-07-18 14:43 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +		//_responses.Remove(subtopic); /* should i remove it? */
Have it your way. e4570eefd0b685db23d99316d389cdbd45649066
Really, try suggestion block.

2024-07-18 14:56 UTC, AlvaroBajceps commented on MVVM/Model/LocalSettings.cs
moved elsewhere. 23fc0694cbe78c4c47d490e296544b73f885e214

2024-07-18 15:01 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
> +		await Task.WhenAll();
I'm sure, it does now. 9ef3f8cdeb25c02319dd0997cae26570d2e5c6d7

2024-07-18 15:20 UTC, AlvaroBajceps commented on MVVM/Model/RoverCommunication.cs
> +		private readonly PressedKeys pressedKeys;
fix in 2829fc4c00a2b3db48e754575bf0402c6e0de2ab

2024-07-18 15:36 UTC, AlvaroBajceps commented on MVVM/Model/RoverCommunication.cs
> +			Task.Run( async () => await RoverCommunication_OnControlStatusChanged(GenerateRoverStatus) );
so what you suggest?
Godot signal (event handler) cannot return `Task` (return type must be `void`).
And changing this method to `async void` changes nothing, in my unsupported opinion at least.

2024-07-18 15:43 UTC, AlvaroBajceps commented on MVVM/Model/Settings/MqttClientOptions.cs
> +		WillPayloadSerializedJson = "{ CommunicationState: 5 }";
removed e2a8c0b568dc3570c25aec5cd41362dc7f3784e4

2024-07-18 15:45 UTC, AlvaroBajceps commented on MVVM/Model/Settings/MqttSubscribedExtension.cs
> +			[
![](https://media1.tenor.com/m/94GsWHDABYwAAAAC/i-see-no-problem-here-crazy-eyes.gif)

2024-07-18 16:13 UTC, AlvaroBajceps commented on MVVM/Model/TargetObjectMirror.cs
> +public class TargetObjectMirror
Have it your way. 1465545b48cc54c50544d8cc657210336ebce097

2024-07-18 18:31 UTC, AlvaroBajceps commented on MVVM/Model/MqttNode.cs
### This was bug caused by rapid connection state change in `MqttNode`.

`Timestamp` was same because time between 2 sequential changes can be lower than 1ms.

`CommunicationState` was same because those 2 events were emitted on end of frame (with `CallDeferred()`), one after another, pulling value from `MqttNode` not from event handler parameter. Value 1 was latest value set to connation state in `MqttNode`.

### Fixed in 3f833b6900f5bf08a12d933321bda23482be62e8
![image](https://github.com/user-attachments/assets/a7cdd157-ad24-4339-9aa1-064fca54d9c9)

2024-07-18 22:44 UTC, Wojtuz commented
Noticed weird behavior in driving mode. When holding 'w', instead of a single message (current master),
![image](https://github.com/user-attachments/assets/93d225c3-feb2-4f75-96d3-67dc82f8026e)

the app sends multiple identical ones.
![image](https://github.com/user-attachments/assets/321ec9fe-0145-4e24-ae1b-03fb07b49dbe)

When using a gamepad that bug does not occur.
![image](https://github.com/user-attachments/assets/a9deab8d-d5a0-417f-ab44-e9190fdeaaa4)

We don't use keyboard inputs often anyway, but I think it's worth looking into

2024-07-19 12:31 UTC, AlvaroBajceps commented
This bug is also present on master, cause of it is located in `EricSOnController`.
Can be missed due to different default settings for controller    
(on master: `ForzaLikeController`; on dev/static-to-instance: `EricSOnController`)

### branch: master
https://github.com/wisniax/RoverControlApp/blob/ba67ebb1d87b23dd6fd88e61feaa528cf761e2af/Core/RoverControllerPresets.cs#L91-L92

### branch: dev/static-to-instance
https://github.com/wisniax/RoverControlApp/blob/45fc48072b714a17da08954c016a1cc87db18046/Core/RoverControllerPresets.cs#L89-L90

swapping axis in vector solves issue. d0fe364d029aee81428e00f13f1f2fdd3cc3354e

2024-07-20 14:31 UTC, wisniax commented on MVVM/Model/RoverCommunication.cs
> +			Task.Run( async () => await RoverCommunication_OnControlStatusChanged(GenerateRoverStatus) );
Not sure myself but `async void`'s been always the way in those cases (When it could not be avoided i think)

2024-07-20 14:54 UTC, AlvaroBajceps commented on MVVM/Model/RoverCommunication.cs
> +			Task.Run( async () => await RoverCommunication_OnControlStatusChanged(GenerateRoverStatus) );
Works better, i suppose. 4951cc74b6143c8683914e2318f1366c7286646e

2024-07-20 15:51 UTC, wisniax reviewed
Overall everything seems to be good. Just one thing bothers me:
![image](https://github.com/user-attachments/assets/6a015110-be9f-4527-b295-11d1a9f424ac)
What's that Axis1 message lmao? Haven't seen it last time ;)

Edit:
Actually it's undocumented year's old feature that we never used (also present on master)
Will have to delete it some day. Now's not the time tho

2024-07-20 15:56 UTC, wisniax approved these changes
All G ;)

2024-07-20 16:04 UTC, merged