Multi camera support v0.5
wisniax/RoverControlApp pull request #26
Opened 2024-08-27 16:26 UTC by Wojtuz

Just multiple cameras. (SD ones for now, HD switching still crashing outside of debug) Rolled back to opencvsharp as it works "at all" on ubuntu 20.04 and there is no chance that I'd get libvlc working before ERC

What still needs to be done:

- [ ] fix crashes when "restarting" rtspclient with a new stream link

- [ ] separate indicators showing when did a client receive a new frame

- [ ] getting rid of PTZ settings from Cameras 1-5

- [ ] possibly UI changes

2024-08-28 12:15 UTC, Wojtuz commented
![image](https://github.com/user-attachments/assets/37fe8059-f2b8-4e92-a693-56eb525fa679)
The focused camera view is obscured by the debug panel "a bit too much" imo. I'll try making it neater.

2024-08-28 19:12 UTC, Wojtuz commented
Seems to work. Still need to figure out the ptz thing. Cannot see a simple way to get rid of ptz settings from only certain camera settings. I've grown to accept the UI but I can make that menu retractable if you want

2024-08-30 12:31 UTC, Wojtuz commented
Implemented all of the above. I'll try putting cam0,1,2... settings in a separeate submenu and it should be fine then. (If we decide that we stay with "rtsplink" instead of separate login pass ip etc we would have get rid of it as well)

2024-08-30 13:43 UTC, Wojtuz commented
![image](https://github.com/user-attachments/assets/983a916b-eac0-4ce9-86bf-bc6f97373c79)
"Just one more tiny thing". That being fullscreen behavior xd

2024-08-30 13:58 UTC, Wojtuz commented
Fixed it. Tell me what you think and I'll get to crabmode

2024-08-30 14:55 UTC, Wojtuz commented
I'll add better handling of the camera labels, maybe custom names while I'm at it

2024-09-01 21:15 UTC, wisniax commented
Whole application crashes on start when no internet / camera connected

2024-09-01 21:21 UTC, wisniax commented
> Whole application crashes on start when no internet / camera connected

Exact issue:
![image](https://github.com/user-attachments/assets/e5d804a2-9296-4095-8414-abdfa0b01c56)
Please check all hot-paths b4 requesting a finished PR

2024-09-01 22:33 UTC, wisniax commented
Also:
![image](https://github.com/user-attachments/assets/bb513656-1233-4948-8da8-59cf1ccf6656)
Viewable settings and the ones actually set DIFFER... WTF??

Please test this ASAP on actually real cameras...
Ready to merge PR is not the place for reviewers to actually TEST the stuff for the **FIRST** time. (notably FIRST)
They absolutely should test the new soft to ensure that it is bug-free but stating that something that doesn't even start (in actual test environment with local cameras) and only shows some russian motel is not IMO smth a REVIEWER should have to point out...

What I'd like to have is when s1 is requesting a review that they exactly mean what follows:
> Hey I've done something, tested it and it actually works so we can implement it. So please

2024-09-01 22:34 UTC, wisniax requested changes
Also:
![image](https://github.com/user-attachments/assets/bb513656-1233-4948-8da8-59cf1ccf6656)
Viewable settings and the ones actually set DIFFER... WTF??

Please test this ASAP on actually real cameras...
Ready to merge PR is not the place for reviewers to actually TEST the stuff for the **FIRST** time. (notably FIRST)
They absolutely should test the new soft to ensure that it is bug-free but stating that something that doesn't even start (in actual test environment with local cameras) and only shows some russian motel is not IMO smth a REVIEWER should have to point out...

What I'd like to have is when s1 is requesting a review that they exactly mean what follows:
> Hey I've done something, tested it and it actually works so we can implement it. So please

2025-10-02 12:25 UTC, closed without merging