Crab Kinematics
wisniax/RoverControlApp pull request #27
Opened 2024-08-31 17:52 UTC by Wojtuz

Added crab kinematics option to direct drive controller. When C/xbox B button is pressed, XAxis, YAxis and 2 for crab control are passed via mqtt message. Debug display not working yet

2024-09-17 15:54 UTC, AlvaroBajceps requested changes
Code quality issues.

2024-09-17 15:54 UTC, AlvaroBajceps commented on Core/LocalSettings.cs
I have different approach:
- Create class storing all cameras e.g. `Settings.Cameras`. This class would hold all cameras e.g. `Camera0`, `Camera1`, [...] .
- Create enum joining name with id for each camera e.g. `Settings.Cameras.CameraId` with `CameraId.Cam1`, `CameraId.Cam2`, [...] . 
- Add method `Settings.Camera GetCameraFromId(Settings.Cameras.CameraId)` to retrieve object from id.

With everything above implemented, RTSP and PTZ client could store `CameraId` on creation and using mentioned method, retrieve settings for the camera. 

RTSP class have already stored id.
Following code:
> https://github.com/wisniax/RoverControlApp/blob/5a0431bbef1766fba0751d68f56c49d39c4342bd/MVVM/Model/RtspStreamClient.cs#L127-L138

Could be replaced with:
```cs
private string GetNewRTSPLink() =>
	return LocalSettings.Singleton.Cameras.GetCameraFromId(id).RtspLink;
```

2024-09-17 15:54 UTC, AlvaroBajceps commented on MVVM/View/MainView.tscn
> +
This button have size of 0. Change my mind.

2024-09-17 15:54 UTC, AlvaroBajceps commented on Core/Settings/CameraConnection.cs
Maybe go with similar approach as in RTSP client (`RtspLink`) and add `PtzLink`. This would get rid of `Ip`, `Login`, `Password`. `PtzPort` and already unused `RtspPort`

2024-09-19 13:52 UTC, Wojtuz commented on Core/RoverControllerPresets/MqttClasses.RoverControlVec2Extension.cs
Adressed in [7edcd27](https://github.com/wisniax/RoverControlApp/pull/36/commits/7edcd275616ee2d024de1143a9fd7dc17717f7c5)
(I'm not good at github xd Wanted to make separate branches for movement modes, cameras, gripper and sampler but somehow when merging them all into a "big one" with all of the features, I updated the source branches too.)

Camera stuff to be adressed in a separate branch

2024-10-12 22:36 UTC, closed without merging