(Actually) usable sampler
wisniax/RoverControlApp pull request #37
Opened 2024-10-07 17:49 UTC by Wojtuz

![image](https://github.com/user-attachments/assets/d40769cd-e312-4349-942d-bd35ffa38dae)
Seems fine.
Sends messages in a form of

```
public class SamplerControl
{
	public float DrillMovement { get; set; } = 0f; //Drill moving up and down. Range [-1, 1]
	public float PlatformMovement { get; set; } = 0f; //Platform moving up and down. Range [-1, 1]
	public float DrillAction { get; set; } = 0f; //Drill drilling (rotating) left and right. Range [-1, 1]
	public bool ExtendContainer1 { get; set; } = false; //Done with a retractable sample container in mind
	public bool ExtendContainer2 { get; set; } = false; //Done with a retractable sample container in mind
	public bool OpenSkibidi { get; set; } = false; //self explanatory
	
	public long Timestamp { get; set; } = DateTimeOffset.Now.ToUnixTimeMilliseconds();
}

```
![image](https://github.com/user-attachments/assets/8bff389b-a19e-4a6e-ad76-0485f7fd93d0)

No repeated messages, gamepad mapping, made in a "standard way".

2024-10-07 18:22 UTC, Wojtuz reviewed
Looks good to me

2024-10-14 15:50 UTC, AlvaroBajceps requested changes

2024-10-14 15:50 UTC, AlvaroBajceps commented on Core/RoverControllerPresets/SamplerControllers/SamplerControler.cs
Misspelled class identifier `SamplerControler` 
should be `SamplerController`

2024-10-14 15:50 UTC, AlvaroBajceps commented on Resources/background.svg.import
this file (source image) is missing

2024-10-14 15:50 UTC, AlvaroBajceps commented on Rover Control App.csproj
> +  </ItemGroup>
why? no code here.
```suggestion
```

2024-11-10 11:32 UTC, AlvaroBajceps commented on Rover Control App.csproj
> +  </ItemGroup>
Fixed in 11b8a4fc4ac120f22934731785d9d121f1698a46

2024-11-10 11:32 UTC, AlvaroBajceps commented on Resources/background.svg.import
fixed in c6d6c0b62ddabd030b330833737451336cb0e0d9

2024-11-10 11:33 UTC, AlvaroBajceps commented on Core/RoverControllerPresets/SamplerControllers/SamplerControler.cs
Fixed in 11b8a4fc4ac120f22934731785d9d121f1698a46

2024-11-10 11:53 UTC, AlvaroBajceps approved these changes
Seems ok, 
Although i can't operate on all axis, i won't block merge as it can be caused by my DS4 pad incompatibility.

2024-11-10 16:17 UTC, wisniax commented
So if I understand correctly THIS PR is just a sampler (meaning the drill) and the actual probe is a different thing?

I'd rather test how it works b4 merge, but that cannot happen for a while now and there's hardly any point of blocking it so anyway I guess...

Just want to see Crab merged first, then we can follow with any conflicts that should arise and merge this one I guess

2024-11-16 13:19 UTC, Wojtuz commented
I heard that the app should send floats (how the servo is supposed to be set) instead of binary on-off so I added that + some QoL.

2024-11-16 13:21 UTC, Wojtuz commented
![image](https://github.com/user-attachments/assets/99451920-0da6-4643-9846-000fc1da4b04)

2024-11-19 11:05 UTC, AlvaroBajceps approved these changes
Still works. 
Yet consider fixing ternary operator overuse issue.

2025-01-09 11:19 UTC, Wojtuz commented on Core/RoverControllerPresets/SamplerControllers/SamplerController.cs
> +					? LocalSettings.Singleton.Sampler.Container2.ClosedDegrees : LocalSettings.Singleton.Sampler.Container2.OpenDegrees : lastState.ContainerDegrees2,
Agreed

2025-01-13 18:13 UTC, merged